/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package amc_practica1;

import java.awt.Color;
import java.awt.Graphics;
import java.io.File;
import java.io.IOException;
import static java.lang.Integer.parseInt;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;


/**
 *
 * @author Oscar Chaves Navarro <ochndev at github.com>
 */
public class PrincipalJFrame extends javax.swing.JFrame {

    
    public static final int EXHAUSTIVO = 0;
    public static final int DYV = 1;
    public static final int PRIM = 2;
    public static final int KRUSKAL = 3;
    
    
    String pathactual;
    String filename;
    String nombre;
    String comentarios;
    String cantidad_puntos;
    LogicaDeLaAplicacion LDLA;
    int numero_puntos = 0;
    int cantidad_inicial = 0;
    int cantidad_final = 0;
    int tipo_analisis = 0;
    ArrayList<Punto> puntos;
    long [] tiempo_medio;
    long [][] tiempos_medios;
    //ArrayList<Punto> triangulo;
    int num_tallas;
    int [] tallas;
    int repeticiones;
    int metodo;
    int [] metodos;
    double distancia_minima;
    Triangulo triangulo;
    boolean caso_peor;
    String nombre_metodo[] = {"EXHAUSTIVO","DIVIDE Y VENCERAS","PRIM","KRUSKAL"};
    
    /**
     * Creates new form PrincipalJFrame
     */
    public PrincipalJFrame() {
        initComponents();
        try{
        setIconImage(new ImageIcon(getClass().getResource("imagenes/icono.jpg")).getImage());
        }catch(Exception e){
            System.out.println("No se encuentra el archivo de ICONO");
        }
        LDLA = new LogicaDeLaAplicacion();
        triangulo = new Triangulo();
        triangulo.setA(new Punto(0,0));
        triangulo.setB(new Punto(0,0));
        triangulo.setC(new Punto(0,0));
        triangulo.setDistancia(10000000);
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos con extension .tsp","tsp");
        jFileChooser.setFileFilter(filter);
        jFileChooser.setCurrentDirectory(new File(".\\"));
        FileNameExtensionFilter filter2 = new FileNameExtensionFilter("Archivos con extension .tour","tour");
        jFileChooser2.setFileFilter(filter2);
        jFileChooser2.setCurrentDirectory(new File(".\\"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser = new javax.swing.JFileChooser();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jDialogConfigurarPuntos = new javax.swing.JDialog();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        ToggleButtonCasoPeor = new javax.swing.JToggleButton();
        jLabel18 = new javax.swing.JLabel();
        jConfigurarPrueba = new javax.swing.JDialog();
        jButtonAceptarConfiguracionPrueba = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButtonCancelarConfiguracionPrueba = new javax.swing.JButton();
        jTallasPrueba = new javax.swing.JTextField();
        jRepeticionesPrueba = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jToggleButton1 = new javax.swing.JToggleButton();
        jFileChooser2 = new javax.swing.JFileChooser();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jRutaLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jFileNameLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        BotonProbarExhaustivo = new javax.swing.JButton();
        BotonCargarArchivo = new javax.swing.JButton();
        BotonGenerarPuntos = new javax.swing.JButton();
        BotonProbarDyV = new javax.swing.JButton();
        BotonProbarPRIM = new javax.swing.JButton();
        BotonProbarKRUSKAL = new javax.swing.JButton();
        BotonSalir = new javax.swing.JButton();
        BotonGuardarResultado = new javax.swing.JButton();
        jPanelSalida = new javax.swing.JPanel();
        canvas1 = new java.awt.Canvas();
        BotonMostrarPuntos = new javax.swing.JButton();
        BotonMostrarTriangulo = new javax.swing.JButton();
        BotonMostrarGrafo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        canvas2 = new java.awt.Canvas();
        ConfigurarPruebaButton = new javax.swing.JButton();
        IniciarPruebaButton = new javax.swing.JButton();
        MostrarGraficaButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        jFileChooser.setBackground(new java.awt.Color(240, 240, 240));
        jFileChooser.setCurrentDirectory(new java.io.File("C:\\"));
            jFileChooser.setDialogTitle("");
            jFileChooser.setToolTipText("");
            jFileChooser.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jFileChooserActionPerformed(evt);
                }
            });

            jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
            jLabel9.setText("CANTIDAD DE PUNTOS");

            jLabel10.setText("-");

            jDialogConfigurarPuntos.setTitle("Configurar puntos aleatorios");
            jDialogConfigurarPuntos.setMinimumSize(new java.awt.Dimension(400, 300));

            jButton1.setText("Aceptar");
            jButton1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
                }
            });

            jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
            jLabel1.setText("Numero de puntos");

            ToggleButtonCasoPeor.setText("PEOR");

            jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
            jLabel18.setText("¿Es caso peor?");

            javax.swing.GroupLayout jDialogConfigurarPuntosLayout = new javax.swing.GroupLayout(jDialogConfigurarPuntos.getContentPane());
            jDialogConfigurarPuntos.getContentPane().setLayout(jDialogConfigurarPuntosLayout);
            jDialogConfigurarPuntosLayout.setHorizontalGroup(
                jDialogConfigurarPuntosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialogConfigurarPuntosLayout.createSequentialGroup()
                    .addGroup(jDialogConfigurarPuntosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jDialogConfigurarPuntosLayout.createSequentialGroup()
                            .addGap(135, 135, 135)
                            .addGroup(jDialogConfigurarPuntosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1)))
                        .addGroup(jDialogConfigurarPuntosLayout.createSequentialGroup()
                            .addGap(104, 104, 104)
                            .addComponent(jLabel18)
                            .addGap(18, 18, 18)
                            .addComponent(ToggleButtonCasoPeor))
                        .addGroup(jDialogConfigurarPuntosLayout.createSequentialGroup()
                            .addGap(164, 164, 164)
                            .addComponent(jButton1)))
                    .addContainerGap(129, Short.MAX_VALUE))
            );
            jDialogConfigurarPuntosLayout.setVerticalGroup(
                jDialogConfigurarPuntosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogConfigurarPuntosLayout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(23, 23, 23)
                    .addGroup(jDialogConfigurarPuntosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18)
                        .addComponent(ToggleButtonCasoPeor))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                    .addComponent(jButton1)
                    .addGap(35, 35, 35))
            );

            jConfigurarPrueba.setTitle("Configurar prueba");
            jConfigurarPrueba.setMinimumSize(new java.awt.Dimension(400, 450));
            jConfigurarPrueba.setPreferredSize(new java.awt.Dimension(360, 450));
            jConfigurarPrueba.setResizable(false);

            jButtonAceptarConfiguracionPrueba.setText("Aceptar");
            jButtonAceptarConfiguracionPrueba.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButtonAceptarConfiguracionPruebaActionPerformed(evt);
                }
            });

            jLabel15.setText("Tallas del problema (separar por comas)");

            jLabel16.setText("Metodo para probar rendimiento ( seleccionar 1 o 2 )");

            jButtonCancelarConfiguracionPrueba.setText("Cancelar");
            jButtonCancelarConfiguracionPrueba.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButtonCancelarConfiguracionPruebaActionPerformed(evt);
                }
            });

            jLabel17.setText("Repeticiones del algoritmo");

            jList2.setModel(new javax.swing.AbstractListModel<String>() {
                String[] strings = { "Método Exhaustivo", "Metodo Divide y Venceras", "Algoritmo de Prim", "Algoritmo de Kruskal" };
                public int getSize() { return strings.length; }
                public String getElementAt(int i) { return strings[i]; }
            });
            jScrollPane2.setViewportView(jList2);

            jToggleButton1.setText("¿Caso Peor?");

            javax.swing.GroupLayout jConfigurarPruebaLayout = new javax.swing.GroupLayout(jConfigurarPrueba.getContentPane());
            jConfigurarPrueba.getContentPane().setLayout(jConfigurarPruebaLayout);
            jConfigurarPruebaLayout.setHorizontalGroup(
                jConfigurarPruebaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jConfigurarPruebaLayout.createSequentialGroup()
                    .addGroup(jConfigurarPruebaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jConfigurarPruebaLayout.createSequentialGroup()
                            .addGap(57, 57, 57)
                            .addGroup(jConfigurarPruebaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel17)
                                .addComponent(jLabel16)
                                .addComponent(jTallasPrueba)
                                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRepeticionesPrueba)
                                .addComponent(jScrollPane2)))
                        .addGroup(jConfigurarPruebaLayout.createSequentialGroup()
                            .addGap(95, 95, 95)
                            .addComponent(jButtonAceptarConfiguracionPrueba)
                            .addGap(18, 18, 18)
                            .addComponent(jButtonCancelarConfiguracionPrueba))
                        .addGroup(jConfigurarPruebaLayout.createSequentialGroup()
                            .addGap(125, 125, 125)
                            .addComponent(jToggleButton1)))
                    .addContainerGap(51, Short.MAX_VALUE))
            );
            jConfigurarPruebaLayout.setVerticalGroup(
                jConfigurarPruebaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jConfigurarPruebaLayout.createSequentialGroup()
                    .addGap(29, 29, 29)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jTallasPrueba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel17)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jRepeticionesPrueba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                    .addComponent(jLabel16)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jToggleButton1)
                    .addGap(34, 34, 34)
                    .addGroup(jConfigurarPruebaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonAceptarConfiguracionPrueba)
                        .addComponent(jButtonCancelarConfiguracionPrueba))
                    .addGap(38, 38, 38))
            );

            jFileChooser2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jFileChooser2ActionPerformed(evt);
                }
            });

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            setTitle("Algoritmica y Modelos de Computacion - Oscar Chaves Navarro");
            setBackground(new java.awt.Color(255, 255, 255));
            setIconImages(null);
            setLocation(new java.awt.Point(300, 150));
            setMinimumSize(new java.awt.Dimension(960, 720));
            setPreferredSize(new java.awt.Dimension(960, 720));
            setSize(new java.awt.Dimension(960, 720));
            getContentPane().setLayout(new java.awt.FlowLayout());

            jTabbedPane1.setAlignmentX(0.0F);
            jTabbedPane1.setAlignmentY(0.0F);
            jTabbedPane1.setMaximumSize(new java.awt.Dimension(960, 720));
            jTabbedPane1.setMinimumSize(new java.awt.Dimension(960, 720));
            jTabbedPane1.setPreferredSize(new java.awt.Dimension(960, 720));

            jPanel1.setPreferredSize(new java.awt.Dimension(950, 950));

            jRutaLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
            jRutaLabel.setText("RUTA DEL ARCHIVO");

            jLabel2.setText("-");

            jFileNameLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
            jFileNameLabel.setText("NOMBRE DEL ARCHIVO");

            jLabel4.setText("-");

            jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
            jLabel5.setText("NOMBRE");

            jLabel6.setText("-");

            jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
            jLabel7.setText("COMENTARIOS");

            jLabel8.setText("-");

            jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
            jLabel11.setText("DIMENSION");

            jLabel12.setText("-");

            javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
            jPanel2.setLayout(jPanel2Layout);
            jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jRutaLabel)
                                .addComponent(jFileNameLabel)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(0, 207, Short.MAX_VALUE)))
                    .addContainerGap())
            );
            jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jRutaLabel)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel2)
                    .addGap(30, 30, 30)
                    .addComponent(jFileNameLabel)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel4)
                    .addGap(28, 28, 28)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel6)
                    .addGap(31, 31, 31)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel8)
                    .addGap(42, 42, 42)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel12)
                    .addContainerGap(98, Short.MAX_VALUE))
            );

            BotonProbarExhaustivo.setText("Probar metodo Exhaustivo");
            BotonProbarExhaustivo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            BotonProbarExhaustivo.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    BotonProbarExhaustivoActionPerformed(evt);
                }
            });

            BotonCargarArchivo.setText("Cargar datos desde archivo ");
            BotonCargarArchivo.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    BotonCargarArchivoActionPerformed(evt);
                }
            });

            BotonGenerarPuntos.setText("Generar puntos aleatoriamente");
            BotonGenerarPuntos.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    BotonGenerarPuntosActionPerformed(evt);
                }
            });

            BotonProbarDyV.setText("Probar metodo DyV");
            BotonProbarDyV.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            BotonProbarDyV.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    BotonProbarDyVActionPerformed(evt);
                }
            });

            BotonProbarPRIM.setText("Probar Algoritmo de Prim");
            BotonProbarPRIM.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            BotonProbarPRIM.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    BotonProbarPRIMActionPerformed(evt);
                }
            });

            BotonProbarKRUSKAL.setText("Probar Algoritmo de Kruskal");
            BotonProbarKRUSKAL.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            BotonProbarKRUSKAL.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    BotonProbarKRUSKALActionPerformed(evt);
                }
            });

            BotonSalir.setForeground(new java.awt.Color(255, 0, 51));
            BotonSalir.setText("Salir");
            BotonSalir.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    BotonSalirActionPerformed(evt);
                }
            });

            BotonGuardarResultado.setText("Guardar resultados Prim y Kruskal");
            BotonGuardarResultado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            BotonGuardarResultado.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    BotonGuardarResultadoActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
            jPanel5.setLayout(jPanel5Layout);
            jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(86, 86, 86)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(BotonGuardarResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BotonGenerarPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BotonProbarDyV, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BotonProbarExhaustivo, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BotonProbarPRIM, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BotonProbarKRUSKAL, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BotonCargarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(BotonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(34, 34, 34)))
                    .addContainerGap(205, Short.MAX_VALUE))
            );
            jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(BotonGenerarPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(BotonCargarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(26, 26, 26)
                    .addComponent(BotonProbarExhaustivo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(BotonProbarDyV, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(BotonProbarPRIM, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(BotonProbarKRUSKAL, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(27, 27, 27)
                    .addComponent(BotonGuardarResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                    .addComponent(BotonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
            );

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(84, 84, 84)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(32, 32, 32)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(100, Short.MAX_VALUE))
            );

            jTabbedPane1.addTab("Inicio", jPanel1);

            jPanelSalida.setPreferredSize(new java.awt.Dimension(940, 720));

            canvas1.setBackground(new java.awt.Color(255, 255, 255));
            canvas1.setMaximumSize(new java.awt.Dimension(500, 500));
            canvas1.setMinimumSize(new java.awt.Dimension(500, 500));
            canvas1.setName(""); // NOI18N

            BotonMostrarPuntos.setText("Mostrar Puntos");
            BotonMostrarPuntos.setToolTipText("");
            BotonMostrarPuntos.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    BotonMostrarPuntosActionPerformed(evt);
                }
            });

            BotonMostrarTriangulo.setText("Mostrar Triangulo");
            BotonMostrarTriangulo.setToolTipText("");
            BotonMostrarTriangulo.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    BotonMostrarTrianguloActionPerformed(evt);
                }
            });

            BotonMostrarGrafo.setText("Mostrar Grafo");
            BotonMostrarGrafo.setToolTipText("");
            BotonMostrarGrafo.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    BotonMostrarGrafoActionPerformed(evt);
                }
            });

            jTextArea2.setColumns(20);
            jTextArea2.setRows(5);
            jScrollPane1.setViewportView(jTextArea2);

            javax.swing.GroupLayout jPanelSalidaLayout = new javax.swing.GroupLayout(jPanelSalida);
            jPanelSalida.setLayout(jPanelSalidaLayout);
            jPanelSalidaLayout.setHorizontalGroup(
                jPanelSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelSalidaLayout.createSequentialGroup()
                    .addGap(65, 65, 65)
                    .addComponent(BotonMostrarPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(BotonMostrarTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(BotonMostrarGrafo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanelSalidaLayout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addComponent(canvas1, javax.swing.GroupLayout.DEFAULT_SIZE, 729, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
            );
            jPanelSalidaLayout.setVerticalGroup(
                jPanelSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelSalidaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanelSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                        .addComponent(canvas1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanelSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BotonMostrarPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BotonMostrarTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BotonMostrarGrafo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(111, Short.MAX_VALUE))
            );

            jTabbedPane1.addTab("Puntos y triangulo", jPanelSalida);

            canvas2.setBackground(new java.awt.Color(255, 255, 255));
            canvas2.setMinimumSize(new java.awt.Dimension(600, 400));

            ConfigurarPruebaButton.setText("Configurar prueba");
            ConfigurarPruebaButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    ConfigurarPruebaButtonActionPerformed(evt);
                }
            });

            IniciarPruebaButton.setText("Iniciar prueba");
            IniciarPruebaButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    IniciarPruebaButtonActionPerformed(evt);
                }
            });

            MostrarGraficaButton.setText("Mostrar gráfica de lineas");
            MostrarGraficaButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    MostrarGraficaButtonActionPerformed(evt);
                }
            });

            jTextArea1.setColumns(20);
            jTextArea1.setRows(5);
            jScrollPane3.setViewportView(jTextArea1);

            javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
            jPanel4.setLayout(jPanel4Layout);
            jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addContainerGap(150, Short.MAX_VALUE)
                    .addComponent(ConfigurarPruebaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(IniciarPruebaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(MostrarGraficaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(169, 169, 169))
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addComponent(canvas2, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(41, 41, 41)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ConfigurarPruebaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(IniciarPruebaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(MostrarGraficaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(canvas2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
                    .addContainerGap(131, Short.MAX_VALUE))
            );

            jTabbedPane1.addTab("Graficas de Rendimiento", jPanel4);

            getContentPane().add(jTabbedPane1);
            jTabbedPane1.getAccessibleContext().setAccessibleName("Inicio");

            getAccessibleContext().setAccessibleDescription("");

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void jFileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooserActionPerformed
        
        String [] texto_etiquetas;
        texto_etiquetas = new String[3];
        
        jFileChooser = (JFileChooser)evt.getSource();
        
        String command = evt.getActionCommand();
        if(command.equals(JFileChooser.APPROVE_SELECTION)){
            File archivoSeleccionado = jFileChooser.getSelectedFile();
            jLabel2.setText(archivoSeleccionado.getAbsolutePath());
            
            try {
                puntos = LDLA.cargarArchivoTSP(archivoSeleccionado.getAbsolutePath(),texto_etiquetas);
            } catch (IOException ex) {
                Logger.getLogger(PrincipalJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            nombre = texto_etiquetas[0];
            comentarios = texto_etiquetas[1];
            cantidad_puntos = texto_etiquetas[2];
            
            jLabel4.setText(archivoSeleccionado.getName());
            jLabel6.setText(nombre);
            jLabel8.setText(comentarios);
            jLabel12.setText(cantidad_puntos);
            
            
        }else if(command.equals(JFileChooser.CANCEL_SELECTION)){
            
        }
    }//GEN-LAST:event_jFileChooserActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        System.out.println(jTextField1.getText());
        numero_puntos = parseInt(jTextField1.getText());
        boolean caso_peor = ToggleButtonCasoPeor.isSelected();
        jDialogConfigurarPuntos.setVisible(false);
        
        //Generamos los puntos aleatoriamente        
        if(!caso_peor){
            puntos = LDLA.generarPuntosAleatorios(numero_puntos);            
            
        }else{
            puntos = LDLA.generarPuntosAleatoriosPeor(numero_puntos);
        }

        jLabel2.setText("-");
        jLabel4.setText("-");
        jLabel6.setText("Random");
        jLabel8.setText("Creacion de puntos aleatorios");
        jLabel12.setText(String.valueOf(numero_puntos));
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BotonMostrarPuntosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMostrarPuntosActionPerformed
        
        Graphics g = canvas1.getGraphics();
        
        int [][] CoordenadasPantalla;
        
        //Primero debemos traducir los puntos a las coordenadas en el lienzo
        System.out.println("puntos: ");
        for(int i = 0 ; i < puntos.size() ; i++)
            System.out.println("x: "+puntos.get(i).getX());
        
        CoordenadasPantalla = LDLA.ConvertirCoordenadasPantalla(puntos, canvas1.getWidth(), canvas1.getHeight());
        
        for(int i = 0 ; i < puntos.size(); i++){
            
            g.setColor(Color.BLACK);
            g.fillOval(CoordenadasPantalla[0][i]-2,CoordenadasPantalla[1][i]-2, 4, 4);
        } 
        
    }//GEN-LAST:event_BotonMostrarPuntosActionPerformed

    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BotonSalirActionPerformed

    private void BotonGenerarPuntosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGenerarPuntosActionPerformed
        
        jDialogConfigurarPuntos.setVisible(true);
        
    }//GEN-LAST:event_BotonGenerarPuntosActionPerformed

    private void BotonCargarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCargarArchivoActionPerformed
        
        jFileChooser.showOpenDialog(this);

    }//GEN-LAST:event_BotonCargarArchivoActionPerformed

    private void BotonProbarExhaustivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonProbarExhaustivoActionPerformed

        
        double distancia_minima = 10000000;        
        
        if(LDLA.cantidad_puntos != 0)
        {
            triangulo = LDLA.probarMetodo(EXHAUSTIVO);
            distancia_minima = triangulo.getDistancia();       
            JOptionPane.showMessageDialog(this, ("Tarea finalizada ("+nombre_metodo[EXHAUSTIVO]+")\ndistancia_minima: " +
                    String.format("%.3f",distancia_minima) +
                    "\npuntos del triangulo: \n[" + triangulo.getA().getX() + " - " + triangulo.getA().getY() +
                    "]\n[" + triangulo.getB().getX() + " - " + triangulo.getB().getY()+
                    "]\n[" + triangulo.getC().getX() + " - " + triangulo.getC().getY())+"]");
        }else{
            
            JOptionPane.showMessageDialog(this, "ERROR - Debe cargar una archivo o generar puntos aleatorios");
            
        }        
        
    }//GEN-LAST:event_BotonProbarExhaustivoActionPerformed

    private void BotonMostrarTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMostrarTrianguloActionPerformed
        
        Graphics g = canvas1.getGraphics();
        
        String salidaTexto = "";
        
        int [][] CoordenadasTriangulo;
        
        ArrayList<Punto> puntos_triangulo = new ArrayList(3);
        puntos_triangulo.add(triangulo.getA());
        puntos_triangulo.add(triangulo.getB());
        puntos_triangulo.add(triangulo.getC());
        
        CoordenadasTriangulo = LDLA.ConvertirCoordenadasPantalla(puntos_triangulo, canvas1.getWidth(), canvas1.getHeight());
        
        g.setColor(Color.RED);
        g.drawLine(CoordenadasTriangulo[0][0], CoordenadasTriangulo[1][0],CoordenadasTriangulo[0][1], CoordenadasTriangulo[1][1]);
        g.drawLine(CoordenadasTriangulo[0][1], CoordenadasTriangulo[1][1],CoordenadasTriangulo[0][2], CoordenadasTriangulo[1][2]);
        g.drawLine(CoordenadasTriangulo[0][2], CoordenadasTriangulo[1][2],CoordenadasTriangulo[0][0], CoordenadasTriangulo[1][0]);
        
        salidaTexto+="Punto A ("+triangulo.getA().getX()+" - "+triangulo.getA().getY()+")\n";
        salidaTexto+="Punto B ("+triangulo.getB().getX()+" - "+triangulo.getB().getY()+")\n";
        salidaTexto+="Punto C ("+triangulo.getB().getX()+" - "+triangulo.getC().getY()+")\n";
        salidaTexto+="Perimetro: "+String.format("%.3f", triangulo.getDistancia());
        
        this.jTextArea2.setText(salidaTexto);
        
    }//GEN-LAST:event_BotonMostrarTrianguloActionPerformed

    private void ConfigurarPruebaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfigurarPruebaButtonActionPerformed
            
        this.jConfigurarPrueba.setVisible(true);
        
    }//GEN-LAST:event_ConfigurarPruebaButtonActionPerformed

    private void jButtonAceptarConfiguracionPruebaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarConfiguracionPruebaActionPerformed
        
        String tallas_aux = jTallasPrueba.getText();
        String [] spliter = tallas_aux.split(",");
        this.metodos = new int [jList2.getSelectedIndices().length];
        
        this.metodos = this.jList2.getSelectedIndices();
        this.num_tallas = spliter.length;
        this.tallas = new int [num_tallas];
        this.repeticiones = parseInt(jRepeticionesPrueba.getText());
        this.caso_peor = this.jToggleButton1.isSelected();
        
        for(int i = 0 ; i < num_tallas; i++)
            tallas[i] = parseInt(spliter[i]);        
        
        jConfigurarPrueba.setVisible(false);
            
    }//GEN-LAST:event_jButtonAceptarConfiguracionPruebaActionPerformed

    private void jButtonCancelarConfiguracionPruebaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarConfiguracionPruebaActionPerformed
            
        jConfigurarPrueba.setVisible(false);
        
    }//GEN-LAST:event_jButtonCancelarConfiguracionPruebaActionPerformed

    private void IniciarPruebaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarPruebaButtonActionPerformed
        
        String mensaje = "";
        String mensaje_area_texto = "";
        tiempos_medios = new long [metodos.length][tallas.length];
        
        for(int i = 0 ; i < metodos.length ; i++)
            tiempos_medios[i] = LDLA.medirTiempoAlgoritmo(tallas , repeticiones , metodos[i], caso_peor);
              
        for(int i = 0; i < metodos.length; i++){
            mensaje = "TAREA FINALIZADA (talla - tiempos): \n";
            mensaje_area_texto += "\nMetodo "+nombre_metodo[metodos[i]]+"\n";
            for(int j = 0; j < tiempos_medios[i].length ; j++){
                mensaje += tallas[j] + "  - " + tiempos_medios[i][j] + " ms\n";
                mensaje_area_texto += tallas[j] + " - " + tiempos_medios[i][j] + " ms\n";
            }
            JOptionPane.showMessageDialog(this,mensaje);
        }
        
        jTextArea1.setText(mensaje_area_texto);
        
        
    }//GEN-LAST:event_IniciarPruebaButtonActionPerformed

    private void BotonProbarDyVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonProbarDyVActionPerformed

        double distancia_minima = 10000000;

        if(LDLA.cantidad_puntos == 0)
        {
            JOptionPane.showMessageDialog(this, "ERROR - Debe cargar una archivo o generar puntos aleatorios");

        
        }else{
            
            triangulo = LDLA.probarMetodo(DYV);
            distancia_minima = triangulo.getDistancia();
        
            JOptionPane.showMessageDialog(this, ("Tarea finalizada ("+nombre_metodo[DYV]+")\ndistancia_minima: " + String.format("%.3f", distancia_minima) +
                "\npuntos del triangulo: \n[" + triangulo.getA().getX() + " - " + triangulo.getA().getY() +
                "]\n[" + triangulo.getB().getX() + " - " + triangulo.getB().getY()+
                "]\n[" + triangulo.getC().getX() + " - " + triangulo.getC().getY())+"]");
            
        }
    }//GEN-LAST:event_BotonProbarDyVActionPerformed

    private void MostrarGraficaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarGraficaButtonActionPerformed
        
        Graphics g = canvas2.getGraphics();
        int anchuraCanvas = canvas2.getWidth();
        int alturaCanvas = canvas2.getHeight();
        
        long maxY = 0;
        
        int [][] CoordenadasPantalla = new int [metodos.length][tallas.length];
        
        //Primero debemos traducir los puntos a las coordenadas en el lienzo
        //Calculamos el maximo Y para la leyenda del eje de abcisas
        //Por cada metodo dibujamos su correspondiente gráfica

        for(int i = 0 ; i < metodos.length ; i++)
            for(int x = 0 ; x < tiempos_medios[i].length ; x++)
                if(maxY < tiempos_medios[i][x])
                    maxY = tiempos_medios[i][x];

        
        for(int i = 0 ; i < metodos.length ; i++){
            
            CoordenadasPantalla = LDLA.ConvertirCoordenadasPantalla(tiempos_medios[i] , tallas , anchuraCanvas-30, alturaCanvas-30 , maxY);

            //Dibujamos las lineas
            for (int j = 0; j < CoordenadasPantalla.length-1; j++) {
             
                g.setColor(Color.BLUE);
                g.drawLine(CoordenadasPantalla[0][j], CoordenadasPantalla[1][j], CoordenadasPantalla[0][j+1], CoordenadasPantalla[1][j+1]);            
            }
            
            //Dibujamos los puntos            
            for(int k = 0; k < tiempos_medios[i].length ; k++){
                
                g.setColor(Color.RED);
                g.fillOval(CoordenadasPantalla[0][k]-2,CoordenadasPantalla[1][k]-2, 5, 5);
            
            }
        
        }
        
        // Representamos un rectangulo alrededor de las graficas
        
        int [] xPoints = { 10 , 10 , anchuraCanvas-10 , anchuraCanvas-10 };
        int [] yPoints = { 10 , alturaCanvas-10, alturaCanvas-10 , 10 };
        
        g.setColor(Color.BLACK);
        g.drawPolygon( xPoints , yPoints , 4);
        
        
        // Representamos la leyenda
        for(int i = 0; i<tallas.length; i++){
            g.setColor( Color.magenta );
            g.drawString( String.valueOf(tallas[i]) , CoordenadasPantalla[0][i] , alturaCanvas-2);

        }
        
        g.drawString( String.valueOf(maxY) , 2 , 10 );
        g.drawString( String.valueOf(Math.round(maxY/2)) , 2 , Math.round(alturaCanvas/2) );
        g.drawString( String.valueOf(Math.round(maxY/4)) , 2 , Math.round(3*alturaCanvas/4) );
        g.drawString( String.valueOf(Math.round(3*maxY/4)) , 2 , Math.round(alturaCanvas/4) );
        
    }//GEN-LAST:event_MostrarGraficaButtonActionPerformed

    private void BotonProbarPRIMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonProbarPRIMActionPerformed

        
        if(LDLA.cantidad_puntos != 0)
        {        
            distancia_minima = LDLA.probarMetodo(PRIM).getDistancia();
            System.out.println("Distancia Minima: " + distancia_minima);
            JOptionPane.showMessageDialog(this, "Tarea finalizada ("+nombre_metodo[PRIM]+")\ndistancia_minima: "+String.format("%.3f",distancia_minima));
        }else{
            JOptionPane.showMessageDialog(this, "ERROR - Cargue un archivo o genere puntos aleatorios");
        }
        
    }//GEN-LAST:event_BotonProbarPRIMActionPerformed

    private void BotonProbarKRUSKALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonProbarKRUSKALActionPerformed
        
        if(LDLA.cantidad_puntos != 0)
        {  
            distancia_minima = LDLA.probarMetodo(KRUSKAL).getDistancia();        
            System.out.println("Distancia Minima: " + distancia_minima);        
            JOptionPane.showMessageDialog(this, "Tarea finalizada ("+nombre_metodo[KRUSKAL]+")\ndistancia_minima: "+String.format("%.3f",distancia_minima));
        }else{
            JOptionPane.showMessageDialog(this, "ERROR - Cargue un archivo o genere puntos aleatorios");
        }
    }//GEN-LAST:event_BotonProbarKRUSKALActionPerformed

    private void BotonGuardarResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGuardarResultadoActionPerformed
        
        jFileChooser2.showSaveDialog(this);

    }//GEN-LAST:event_BotonGuardarResultadoActionPerformed

    private void BotonMostrarGrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMostrarGrafoActionPerformed
        
        Graphics g = canvas1.getGraphics();
        
        int [][] CoordenadasGrafo;
        
        CoordenadasGrafo = LDLA.ConvertirCoordenadasPantallaGrafo(LDLA.conjunto_solucion, canvas1.getWidth(), canvas1.getHeight());
        
        g.setColor(Color.GREEN);        
        
        for(int i = 0 ; i < CoordenadasGrafo[0].length ; i++){
            
                g.drawLine(CoordenadasGrafo[0][i],CoordenadasGrafo[1][i],CoordenadasGrafo[2][i],CoordenadasGrafo[3][i]);
                
        }        
        
    }//GEN-LAST:event_BotonMostrarGrafoActionPerformed

    private void jFileChooser2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser2ActionPerformed
        
        jFileChooser2 = (JFileChooser)evt.getSource();
        
        String command = evt.getActionCommand();
        if(command.equals(JFileChooser.APPROVE_SELECTION)){
            File archivoSeleccionado = jFileChooser2.getSelectedFile();
            System.out.println(archivoSeleccionado.getAbsolutePath());
            System.out.println(archivoSeleccionado.getName());

            System.out.println("distancia_minima: "+distancia_minima);
            
            try {
                LDLA.GuardarArchivoTSP(archivoSeleccionado.getParent(),archivoSeleccionado.getName(), String.valueOf(distancia_minima));
                JOptionPane.showMessageDialog(this, "Archivo guardado con exito");
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Ha habido un error al guardar el archivo");
            }            
            
        }else if(command.equals(JFileChooser.CANCEL_SELECTION)){
            
        }
        
        

        
    }//GEN-LAST:event_jFileChooser2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new PrincipalJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonCargarArchivo;
    private javax.swing.JButton BotonGenerarPuntos;
    private javax.swing.JButton BotonGuardarResultado;
    private javax.swing.JButton BotonMostrarGrafo;
    private javax.swing.JButton BotonMostrarPuntos;
    private javax.swing.JButton BotonMostrarTriangulo;
    private javax.swing.JButton BotonProbarDyV;
    private javax.swing.JButton BotonProbarExhaustivo;
    private javax.swing.JButton BotonProbarKRUSKAL;
    private javax.swing.JButton BotonProbarPRIM;
    private javax.swing.JButton BotonSalir;
    private javax.swing.JButton ConfigurarPruebaButton;
    private javax.swing.JButton IniciarPruebaButton;
    private javax.swing.JButton MostrarGraficaButton;
    private javax.swing.JToggleButton ToggleButtonCasoPeor;
    private java.awt.Canvas canvas1;
    private java.awt.Canvas canvas2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAceptarConfiguracionPrueba;
    private javax.swing.JButton jButtonCancelarConfiguracionPrueba;
    private javax.swing.JDialog jConfigurarPrueba;
    private javax.swing.JDialog jDialogConfigurarPuntos;
    private javax.swing.JFileChooser jFileChooser;
    private javax.swing.JFileChooser jFileChooser2;
    private javax.swing.JLabel jFileNameLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelSalida;
    private javax.swing.JTextField jRepeticionesPrueba;
    private javax.swing.JLabel jRutaLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTallasPrueba;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
